language: node_js
node_js: 
   "10.7.0"
before_script:
  - npm install
  - psql -c 'create database test_db;' -U postgres

script:
- npm run create
- npm run test

after_success:
- npm run test:coveralls

